headers:
  x-frame-options: SAMEORIGIN
  cache-control: public, max-age=31536000
  x-content-type-options: nosniff
  content-security-policy:
    default: 'self' 'unsafe-inline' 'unsafe-eval'
    img: *
    fonts: *
    frames: *
    styles: * 'unsafe-inline'
    js: * 'unsafe-inline'

CORS:
  origin: "*"
  methods: GET, POST, OPTIONS, PUT, DELETE, PATCH
  headers: "*"
  age": 86400