headers:
  x-frame-options: SAMEORIGIN
  cache-control: public, max-age=31536000
  x-content-type-options: nosniff
  content-security-policy:
    default-src: "'self' 'unsafe-inline' 'unsafe-eval'"
    img-src: "* 'self' data: https:"
    font-src: *
    frame-src: *
    style-src-elem: * 'unsafe-inline'
    script-src-elem: * 'unsafe-inline'

CORS:
  origin: "*"
  methods: GET, POST, OPTIONS, PUT, DELETE, PATCH
  headers: "*"
  age": 86400